Add packages required by grpcio on devcontainer
When running `pip3 install --user -r zephyr/scripts/requirements.txt`
(last step on https://zmk.dev/docs/development/setup), grpcio install
fails with the following error:

    FileNotFoundError: [Errno 2] No such file or directory: c++: c++

This error is issue https://github.com/grpc/grpc/issues/24556